model: resnet
batch_size:
    top: 16
    all: 4
epochs:
    top: 1
    all: 1
data_aug: true
datafiles:
    train:
      -./infiles/pa_2014_ann_train.txt
      -./infiles/pa_2014_spartadd_train.txt
      -./infiles/pa_2014_juncadd_train.txt
    val:
      -./infiles/pa_2014_ann_val.txt
      -./infiles/pa_2014_spartadd_val.txt
      -./infiles/pa_2014_juncadd_val.txt
    test:
      -./infiles/pa_2014_ann_val.txt
      -./infiles/pa_2014_spartadd_val.txt
      -./infiles/pa_2014_juncadd_val.txt
